### ISSUE TITLE
添加新的data数据之后如何生成新的静态文件？

### ISSUE THREAD

**Issue by imoyao** [flinhong/colors#1]
你好，假如我更新了data数据，如何生成新的index和jp-index呢？我看到你的`_includes/colors-build.html`应该是根据data生成页面的逻辑，但是具体用什么工具或者命令呢？
翻看了你的博客[Bootstrap cards for showing colors | inDev. Journal](https://frankindev.com/2017/11/06/bootstrap-cards-for-colors/)里面是前端页面css的设计思路，没有找到整个流程之类的说明，而readme也只是一个简单介绍。
我有hexo使用经验，Python代码也可以自己编写。但是不知道数据到页面这一步如何完成。
期待你的回复，感谢。

**Comment by flinhong** [comment]
> 你好，假如我更新了data数据，如何生成新的index和jp-index呢？我看到你的`_includes/colors-build.html`应该是根据data生成页面的逻辑，但是具体用什么工具或者命令呢？
> 翻看了你的博客[Bootstrap cards for showing colors | inDev. Journal](https://frankindev.com/2017/11/06/bootstrap-cards-for-colors/)里面是前端页面css的设计思路，没有找到整个流程之类的说明，而readme也只是一个简单介绍。
> 我有hexo使用经验，Python代码也可以自己编写。但是不知道数据到页面这一步如何完成。
> 期待你的回复，感谢。

啊哈，这个有些年月了……让我回忆一下。

最终的静态页应该不是自动生成的，所以我没写怎么瞎搞的步骤😂

下面简单说说吧：

> 在用 Jekyll 生成 html 的时候，最外面 `index.html` 里第一次用的 `{% include colors-build.html %}` 这个。虽然这样生成的页面能正常工作，但是 jquery.peity 遍历渲染那么多个 svg 数据图比较慢，浏览器就会卡卡的。所以我把这时候生成的静态页在浏览器中打开，再把最终包含所有 peity 处理完成的 html 片段拷贝到 `_includes/colors.html` 里，然后回到 `index.html` 那里改成 `{% include colors.html %}`。再用 Jekyll 生成静态页就可以了，我应该是把这个最终的静态页手动复制到 `docs` 文件夹里面的吧。
>
> 其实你看看 `colors-build.html` 和 `colors.html` 这两个文件，`colors.html` 只是包含了 jquery.peity 生成的所有 svg 部分。

不知道说清楚了没～😊

**Comment by imoyao** [comment]
> > 你好，假如我更新了data数据，如何生成新的index和jp-index呢？我看到你的`_includes/colors-build.html`应该是根据data生成页面的逻辑，但是具体用什么工具或者命令呢？
> > 翻看了你的博客[Bootstrap cards for showing colors | inDev. Journal](https://frankindev.com/2017/11/06/bootstrap-cards-for-colors/)里面是前端页面css的设计思路，没有找到整个流程之类的说明，而readme也只是一个简单介绍。
> > 我有hexo使用经验，Python代码也可以自己编写。但是不知道数据到页面这一步如何完成。
> > 期待你的回复，感谢。
> 
> 啊哈，这个有些年月了……让我回忆一下。
> 
> 最终的静态页应该不是自动生成的，所以我没写怎么瞎搞的步骤😂
> 
> 下面简单说说吧：
> 
> > 在用 Jekyll 生成 html 的时候，最外面 `index.html` 里第一次用的 `{% include colors-build.html %}` 这个。虽然这样生成的页面能正常工作，但是 jquery.peity 遍历渲染那么多个 svg 数据图比较慢，浏览器就会卡卡的。所以我把这时候生成的静态页在浏览器中打开，再把最终包含所有 peity 处理完成的 html 片段拷贝到 `_includes/colors.html` 里，然后回到 `index.html` 那里改成 `{% include colors.html %}`。再用 Jekyll 生成静态页就可以了，我应该是把这个最终的静态页手动复制到 `docs` 文件夹里面的吧。
> > 其实你看看 `colors-build.html` 和 `colors.html` 这两个文件，`colors.html` 只是包含了 jquery.peity 生成的所有 svg 部分。
> 
> 不知道说清楚了没～😊

就说我在手机浏览器上操作的时候感觉卡卡的。好的，非常感谢你的耐心解答。
